# REF

http://www.dataquest.io/blog/numpy-tutorial-python/?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more

# CODE

In [8]:
import csv

with open('winequality-red.csv', 'r') as f:
    wines = list(csv.reader(f, delimiter=';'))

In [9]:
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [10]:
qualities = [float(item[-1]) for item in wines[1:]]
sum(qualities) / len(qualities)

5.6360225140712945

In [12]:
import numpy as np
wines = np.array(wines[1:], dtype=np.float)

In [13]:
wines

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [14]:
wines.shape

(1599, 12)

In [15]:
empty_array = np.zeros((3,4))
empty_array

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
np.random.rand(3, 4)

array([[ 0.77051891,  0.8808967 ,  0.27783662,  0.07636765],
       [ 0.09058356,  0.36458777,  0.7725411 ,  0.4846692 ],
       [ 0.18883434,  0.56864269,  0.60681074,  0.66080559]])

In [18]:
wines = np.genfromtxt('winequality-red.csv', delimiter=';', skip_header=1)

In [27]:
wines[2,3]

2.2999999999999998

In [21]:
wines[:3, 3]

array([ 1.9,  2.6,  2.3])

In [31]:
third_wine = wines[3, :]

In [33]:
third_wine[1]

0.28000000000000003

In [38]:
earnings = [
    [
        [500,505,490],
        [810,450,678],
        [234,897,430],
        [560,1023,640]
    ],
    [
        [600,605,490],
        [345,900,1000],
        [780,730,710],
        [670,540,324]
    ]
]
earnings = np.array(earnings)

In [39]:
earnings.shape

(2, 4, 3)

In [40]:
earnings[:, 0, :]

array([[500, 505, 490],
       [600, 605, 490]])

In [41]:
rand_array = np.random.rand(12)
wines + rand_array

array([[  7.67498219,   1.00300245,   0.50117976, ...,   0.65965808,
         10.20869937,   5.51491546],
       [  8.07498219,   1.18300245,   0.50117976, ...,   0.77965808,
         10.60869937,   5.51491546],
       [  8.07498219,   1.06300245,   0.54117976, ...,   0.74965808,
         10.60869937,   5.51491546],
       ..., 
       [  6.57498219,   0.81300245,   0.63117976, ...,   0.84965808,
         11.80869937,   6.51491546],
       [  6.17498219,   0.94800245,   0.62117976, ...,   0.80965808,
         11.00869937,   5.51491546],
       [  6.27498219,   0.61300245,   0.97117976, ...,   0.75965808,
         11.80869937,   6.51491546]])

In [42]:
wines[:,11].sum()

9012.0

In [50]:
wines.shape

(1599, 12)

In [48]:
wines.sum(axis=0).shape

(12,)

In [57]:
wines.sum(axis=1).shape

(1599,)

In [55]:
high_quality = wines[:,11] > 7
wines[high_quality,:][:3].shape

(3, 12)

In [56]:
array_one = np.array(
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8]
    ]
)

array_one.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])